name: 'Send JSON Files with cURL'
description: 'Sends JSON files with cURL'

inputs:
  directory-path:
    description: 'Path to the JSON file for extracting API URL'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Send JSON Files with cURL
      shell: bash
      run: |
        # Set the Directory Path of the config file in Integration
        DIRECTORY_PATH="${{ inputs.directory-path }}"

        # Json file sent as payload
        response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -d @"$DIRECTORY_PATH" "$API_URL")
        echo "RESPONSE_CODE=${response_code}" 
