name: 'Send JSON Files with cURL'
description: 'Sends JSON files with cURL'

inputs:
  directory-path:
    description: 'Path to the JSON file for extracting API URL'
    required: true
  environment:
    description: 'The environment in which reprocessing service is run on'
    required: true
  function-key-secret-dev:
    description: 'The github secret for dev passed as an input'
    required: true 
  function-key-secret-int:
    description: 'The github secret for dev passed as an input'
    required: true              

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Extract API URL
      id: extract-api-url
      shell: bash
      run: |
        DIRECTORY_PATH="${{ inputs.directory-path }}"
        API_URL=$(jq -r '.url' $DIRECTORY_PATH)
        echo "API_URL=${API_URL}" >> $GITHUB_ENV

    # - name: Use GitHub secrets in composite action
    #   shell: bash
    #   run: |
    #     echo "FUNCTION_KEY_SECRET_DEV=${{ inputs.function-key-secret-dev }}"
    #     echo "FUNCTION_KEY_SECRET_INT=${{ inputs.function-key-secret-int }}"

    - name: Send JSON Files with cURL
      shell: bash
      run: |
        # Set the Directory Path of the config file in Integration
        DIRECTORY_PATH="${{ inputs.directory-path }}"

        # # Json file sent as payload
        # response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -d @"$DIRECTORY_PATH" "$API_URL")
        # echo "RESPONSE_CODE=${response_code}" 

        if [ "${{ inputs.environment }}" == "dev" ]; then
            response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -H "x-functions-key: ${{ inputs.function-key-secret-dev }}" -d '"name": "HelloToAzure"' "$API_URL")
        elif [ "${{ inputs.environment }}" == "int" ]; then
            response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -H "x-functions-key: ${{ inputs.function-key-secret-int }}" -d '"name": "HelloToAzure"' "$API_URL")
        elif [ "${{ inputs.environment }}" == "prod" ]; then
            response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -H "x-functions-key: $FUNCTION_KEY_SECRET_PROD" -d '"name": "HelloToAzure"' "$API_URL")
        else
            echo "Unknown Environment Specified"
        fi

