name: 'Post JSON Action'

inputs:
  json-path:
    description: 'Path to the JSON file'
    required: true
  api-endpoint:
    description: 'API endpoint for POST request'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Check for Changes
      id: changes
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep ${{ inputs.json-path }} || true)
        echo "Changed files: $CHANGED_FILES"
        echo "::set-output name=changed_files::${CHANGED_FILES}"

    - name: Run Curl POST
      if: steps.changes.outputs.changed_files
      run: |
        curl -X POST -H "Content-Type: application/json" -d "@${{ inputs.json-path }}" ${{ inputs.api-endpoint }}