name: 'Extract API URL'
description: 'Extracts API URL from JSON file'

inputs:
  directory-path:
    description: 'Path to the JSON file for extracting API URL'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Extract API URL
      id: extract-api-url
      shell: bash
      run: |
        DIRECTORY_PATH="${{ inputs.directory-path }}"
        API_URL=$(jq -r '.url' $DIRECTORY_PATH)
        echo "API_URL=${API_URL}" >> $GITHUB_ENV