name: 'Kafka Reprocessing Integration'

on:
  push:
    branches:
      - feature/testing
    paths:
      - 'reprocessing_configuration/int/*.json'
  pull_request:
    paths:
      - 'reprocessing_configuration/int/*.json'

jobs:
  callingServiceComposite_int:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3        

      - name: Send JSON Files with cURL
        uses: ./.github/actions/send-json-files
        with:
          directory-path: 'reprocessing_configuration/int/*.json'