name: 'Deploy Workflow'

on:
  push:
    branches:
      - feature/prod

jobs:
  deploy-int:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Use Composite Action - Dev
        uses: ./jsoners/setup-composite
        with:
          json-path: 'reprocessing_configuration/dev/config.json'
          api-endpoint: 'https://ca0b-176-198-203-166.ngrok-free.app'