name : Kafka Reprocessing Integration

on:
  push:
    branches:
      - prod
    paths:
      - 'reprocessing/dev/*.json'
  pull_request:
     paths:
      - 'reprocessing/dev/*.json'

jobs:
  callingService_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Include Common Workflow
        uses: ./.github/workflows/common-workflow.yml  

      - name: Send JSON Files with cURL
        run: |
          # Set the API endpoint URL
          # API_URL="https://384e-2a02-908-13b9-38e0-8091-f90b-a163-a12d.ngrok-free.app"
          # DIRECTORY_PATH="reprocessing/dev/*.json"
          # Send Json Files
            response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -d @"$DIRECTORY_PATH_DEV" "$API_URL_DEV")
            if [[ -n "$response_code" && "$response_code" =~ ^[0-9]+$ ]]; then
            if [ "$response_code" -eq 200 ]; then
              echo "Request was successful."
            else
              echo "Request failed with status code: $response_code"
            fi
            else
              echo "Invalid or empty response code: $response_code"
            fi
        