name : Kafka Reprocessing Integration

on:
  push:
    branches:
      - prod
    paths:
      - 'reprocessing/dev/*.json'
  pull_request:
     paths:
      - 'reprocessing/dev/*.json'

jobs:
  callingService_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Files with cURL
        run: |
          # Set the API endpoint URL
          API_URL="https://example.org"
          # Iterate over JSON files in the folder and send them with cURL
          for json_file in "reprocessing/dev/"*.json; do
            json_content=$(cat "$json_file")
            RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d "$json_content" "$API_URL")
            echo "CURL_RESPONSE=${RESPONSE}" >> $GITHUB_ENV
          done

      # - name: cURL request
      #   run: |
      #     # Set the API endpoint URL
        