name: Kafka Reprocessing Integration

on:
  push:
    branches:
      - prod
    paths:
      - 'reprocessing_configuration/dev/*.json'
  pull_request:
     paths:
      - 'reprocessing_configuration/dev/*.json'

jobs:
  callingService_dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory_path:
          - "reprocessing_configuration/int/*.json"
          - "reprocessing_configuration/dev/*.json"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Curl POST Template
        uses: ./.github/actions/curl-template.yml
        with:
          matrix:
            directory_path: ${{ matrix.directory_path }}