# ========================================================================
#  Manually executed Github Actions script to execute the CI-CD pipeline
#  for running the kafka reprocessing service.
# ========================================================================
name: Manual_launch_kafka_reprocessing

on:

  # This script must be executed manually in Github Actions.
  workflow_dispatch:
    inputs:
      target_environment:
        required: true
        description: 'Which Environment should be the reprocessing run on?'
        default: ""
        type: choice
        options:
        - dev
        - int
        - prod

jobs:

  # This job calls script CD.yml only when a push to AWS PROD-CLONE is requested.
  call-reprocessing-int:
    needs: call_reprocessing_int
    if: ${{ inputs.target_environment == 'dev' }}
    uses: ./.github/workflows/kafka-reprocessing-int.yml
    secrets:
      api_Key: "${{ secrets.api_Key }}"
    with:
      api_url: "https://<int-url>"

  # This job calls script CD.yml only when a push to AWS PROD-CLONE is requested.
  call-reprocessing-dev:
    needs: call_reprocessing_dev
    if: ${{ inputs.target_environment == 'dev' }}
    uses: ./.github/workflows/kafka-reprocessing-dev.yml
    secrets:
      api_Key: "${{ secrets.api_Key }}"
    with:
      api_url: "https://<dev-url>3"

  # This job calls script CD.yml only when a push to AWS PROD-CLONE is requested.
  call-reprocessing-prod:
    needs: call_reprocessing_prod
    if: ${{ inputs.target_environment == 'prod' }}
    uses: ./.github/workflows/kafka-reprocessing-prod.yml
    secrets:
      api_Key: "${{ secrets.api_Key }}"
    with:
      api_url: "https://<prod-url>"