name: Kafka Reprocessing Integration

on:
  push:
    branches:
      - prod
    paths:
      - 'reprocessing_configuration/dev/config.json'
  pull_request:
     paths:
      - 'reprocessing_configuration/dev/config.json'

jobs:
  callingService_dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory_path:
          - "reprocessing_configuration/int/config.json"
          - "reprocessing_configuration/dev/config.json"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Curl POST Template
        uses: ./.github/workflows/action.yml